### ISSUE TITLE
nftables ruleset

### ISSUE THREAD

**Issue by petrarca-arezzo** [steinex/tor-ddos#1]
Sounds very nice and logic. I have only very rough knowledge about firewall rules, but at least I have a few rules (working nice) set up - however using nftables (which seems to be the successor of iptables). Do you have the ruleset for nft at hand as well maybe?

**Comment by steinex** [comment]
Hi,

I never touched nftables in my life and will probably not in the foreseeable future, sorry. As far as I'm aware there are wrapper-scripts that can translate one to another? Maybe this can help you?

Other than that I have no idea and don't plan anything soon here, sorry.
