### ISSUE TITLE
More IP addresses for Snowflake bridges

### ISSUE THREAD

**Issue by uumaro** [steinex/tor-ddos#2]
Since https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/issues/40223, the snowflake-01 bridge has 5 outgoing IP addresses. One of them is the same as the forward DNS of snowflake-01.torproject.net, but the other four are different. It would be helpful if the rules excepted the other four addresses as well. See corresponding changes in https://github.com/toralf/torutils/issues/7 and https://github.com/Enkidu-6/tor-ddos/issues/25.

```
193.187.88.42 (existing)
193.187.88.43
193.187.88.44
193.187.88.45
193.187.88.46
2a0c:dd40:1:b::42 (existing)
2a0c:dd40:1:b::43
2a0c:dd40:1:b::44
2a0c:dd40:1:b::45
2a0c:dd40:1:b::46
```

Besides that, there is now a separate snowflake-02 bridge, running at a different site. It was included in [Tor Browser 12.0](https://blog.torproject.org/new-release-tor-browser-120/) released 2022-12-07, so it will start to receive traffic now. At this point it only has one outgoing IP address (one each for IPv4 and IPv6).

```
141.212.118.18
2607:f018:600:8:be30:5bff:fef1:c6fa
```

Cc @ln5

**Comment by steinex** [comment]
Thanks for letting me know. I hope I can get ths implemented tomorrow :-)
